// <auto-generated />
namespace ModelsLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _9904201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_9904201));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100812272_990420-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
